version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pacbook-store-data
    restart: always
    environment:
      POSTGRES_DB: ${SRC_POSTGRES_DB}
      POSTGRES_USER: ${SRC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SRC_POSTGRES_PASSWORD}
    ports:
      - ${SRC_POSTGRES_PORT}:5432
    volumes:
      - ./helper/src/:/docker-entrypoint-initdb.d
      - source-volume:/var/lib/postgresql/data


  dwh:
      image: postgres:latest
      container_name: pacbook-dwh
      restart: always
      environment:
        - POSTGRES_DB=${DWH_POSTGRES_DB}
        - POSTGRES_USER=${DWH_POSTGRES_USER}
        - POSTGRES_PASSWORD=${DWH_POSTGRES_PASSWORD}
      ports:
        - ${DWH_POSTGRES_PORT}:5432
      volumes:
        - dwh_volume:/var/lib/postgresql/data
        - ./helper/dwh/:/docker-entrypoint-initdb.d

volumes:
  source-volume:
  dwh_volume: