TRUNCATE TABLE pacbook.address CASCADE;
TRUNCATE TABLE pacbook.address_status CASCADE ;
TRUNCATE TABLE pacbook.author CASCADE;
TRUNCATE TABLE pacbook.book CASCADE;
TRUNCATE TABLE pacbook.book_author CASCADE;
TRUNCATE TABLE pacbook.book_language CASCADE;
TRUNCATE TABLE pacbook.country CASCADE;
TRUNCATE TABLE pacbook.cust_order CASCADE;
TRUNCATE TABLE pacbook.customer CASCADE;
TRUNCATE TABLE pacbook.customer_address CASCADE;
TRUNCATE TABLE pacbook.order_history CASCADE;
TRUNCATE TABLE pacbook.order_line CASCADE;
TRUNCATE TABLE pacbook.order_status CASCADE;
TRUNCATE TABLE pacbook.publisher CASCADE;
TRUNCATE TABLE pacbook.shipping_method CASCADE;