dbt_transform:
  outputs:
    dev:
      dbname: pacbook-dwh
      host: localhost
      pass: pw123
      port: 5447
      schema: final
      threads: 1
      type: postgres
      user: postgres
  target: dev